apiVersion: v1
kind: Service
metadata:
  labels:
    app: repo-nexus
  name: repo-nexus
  namespace: repo-nexus
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      name: repo-base
    - port: 8082
      targetPort: 8082
      name: repo-docker-hosted
    - port: 8083
      targetPort: 8083
      name: repo-docker-group
  selector:
    app: repo-nexus
